# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: messages.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'messages.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emessages.proto\x12\x06\x63ustom\"U\n\tCustomTel\x12\x11\n\ttimestamp\x18\x01 \x01(\x01\x12\x13\n\x0btemperature\x18\x02 \x01(\x02\x12\x10\n\x08pressure\x18\x03 \x01(\x02\x12\x0e\n\x06status\x18\x04 \x01(\t\"\xbb\x03\n\x08UkfState\x12\x11\n\ttimestamp\x18\x01 \x01(\x04\x12\x12\n\nposition_x\x18\x02 \x01(\x01\x12\x12\n\nposition_y\x18\x03 \x01(\x01\x12\x12\n\nposition_z\x18\x04 \x01(\x01\x12\x14\n\x0cquaternion_w\x18\x05 \x01(\x01\x12\x14\n\x0cquaternion_x\x18\x06 \x01(\x01\x12\x14\n\x0cquaternion_y\x18\x07 \x01(\x01\x12\x14\n\x0cquaternion_z\x18\x08 \x01(\x01\x12\x12\n\nvelocity_x\x18\t \x01(\x01\x12\x12\n\nvelocity_y\x18\n \x01(\x01\x12\x12\n\nvelocity_z\x18\x0b \x01(\x01\x12\x0f\n\x07heading\x18\x0c \x01(\x01\x12\t\n\x01g\x18\x0e \x01(\x01\x12\x0c\n\x04roll\x18\x0f \x01(\x01\x12\r\n\x05pitch\x18\x10 \x01(\x01\x12\x13\n\x0bgyro_bias_x\x18\x11 \x01(\x01\x12\x13\n\x0bgyro_bias_y\x18\x12 \x01(\x01\x12\x13\n\x0bgyro_bias_z\x18\x13 \x01(\x01\x12\x14\n\x0c\x61\x63\x63\x65l_bias_x\x18\x14 \x01(\x01\x12\x14\n\x0c\x61\x63\x63\x65l_bias_y\x18\x15 \x01(\x01\x12\x14\n\x0c\x61\x63\x63\x65l_bias_z\x18\x16 \x01(\x01\x12\x12\n\ncovariance\x18\x17 \x03(\x01\"\x14\n\x03NIS\x12\r\n\x05value\x18\x01 \x01(\x01\"\x15\n\x04NEES\x12\r\n\x05value\x18\x01 \x01(\x01\"0\n\rPositionError\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\"K\n\rVelocityError\x12\x12\n\nvelocity_x\x18\x01 \x01(\x01\x12\x12\n\nvelocity_y\x18\x02 \x01(\x01\x12\x12\n\nvelocity_z\x18\x03 \x01(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'messages_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CUSTOMTEL']._serialized_start=26
  _globals['_CUSTOMTEL']._serialized_end=111
  _globals['_UKFSTATE']._serialized_start=114
  _globals['_UKFSTATE']._serialized_end=557
  _globals['_NIS']._serialized_start=559
  _globals['_NIS']._serialized_end=579
  _globals['_NEES']._serialized_start=581
  _globals['_NEES']._serialized_end=602
  _globals['_POSITIONERROR']._serialized_start=604
  _globals['_POSITIONERROR']._serialized_end=652
  _globals['_VELOCITYERROR']._serialized_start=654
  _globals['_VELOCITYERROR']._serialized_end=729
# @@protoc_insertion_point(module_scope)
